services:
  # BD PostgreSQL
  projet_nuxt.db:
    image: 'postgres:latest'
    env_file: ./projet_nuxt.env
    ports:
      - '5432:5432'

  #
  # service administration des bases sql
  #
  adminer:
    image: 'adminer:latest'
    ports:
      - '8111:8080'

  
  projet_nuxt.frontend:
    build:
      context: .
      dockerfile: build/DockerFile.frontend
    container_name: projetNuxt-frontend
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./application_projet:/app
      - /app/node_modules # Volume temporaire pour préserver les dépendances